Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -2,11 +2,10 @@ name: Update IP List
 
 on:
   schedule:
-    - cron: '0 */1 * * *' # 每3小时运行一次
+    - cron: '0 */1 * * *' # 每1小时运行一次
   workflow_dispatch: # 允许手动触发
 
 jobs:
-
   update-ip-list:
     runs-on: ubuntu-latest
     
@@ -28,12 +27,29 @@ jobs:
       uses: Mattraks/delete-workflow-runs@v2
       with:
         token: ${{ github.token }}
-        repository: ${{ github.repository }}
+        仓库: ${{ github.repository }}
         retain_days: 2
         keep_minimum_runs: 6
         
     - name: Run script
       run: python ${{ github.workspace }}/collect_ips.py
+      
+    - name: Debug file existence
+      run: |
+        echo "Checking for ip.txt and ipv6.txt"
+        ls -l ip.txt ipv6.txt || echo "One or both files not found"
+        if [ -f ip.txt ]; then
+          echo "ip.txt contents:"
+          cat ip.txt
+        else
+          echo "ip.txt does not exist"
+        fi
+        if [ -f ipv6.txt ]; then
+          echo "ipv6.txt contents:"
+          cat ipv6.txt
+        else
+          echo "ipv6.txt does not exist"
+        fi
         
     - name: Commit and push changes
       run: |
